name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: 'sa-east-1'
      TERRAFORM_VERSION: "1.10.2"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          submodules: true
          fetch-depth: 1

      - name: Install Terraform
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Verify Terraform version
        run: terraform version

      - name: Terraform init
        run: |
          terraform init -input=false

      - name: Terraform validation
        run: |
          terraform validate

      - name: Terraform destroy
        id: destroy
        run: |
          terraform destroy -auto-approve
